### ISSUE TITLE
publish latest build to nuget.org

### ISSUE THREAD

**Issue by waynebrantley** [signalwire/signalwire-dotnet#99]
Last publish to nuget was oct 2019.
There have been many commits and versions since then.  
Can this be updated - please advise.

**Comment by bryanrite** [comment]
@waynebrantley Thanks for this, and I understand your concern at using a package that hasn't been updated in a year! The only bits missing from the current Nuget package are internal enhancements to the reconnection logic and some additional testing. All new Relay  or LaML functionality that has been added over the last year has not required any SDK code changes, so you are not missing out on anything due to the date of the last release.

That being said, there is no reason to not update the SDK, so we'll review it and get an update pushed out soon.
